import Link from "next/link";
import { humanizeEnum } from "@/lib/ui/labels";
import { requirePageUser } from "@/lib/auth/page";
import { prisma } from "@/lib/prisma";

export default async function AiTransparencyPage() {
  const user = await requirePageUser(["RECRUITER", "HIRING_MANAGER", "ADMIN"]);
  if (!user.companyId && user.role !== "ADMIN") return null;
  const where = user.role === "ADMIN" ? {} : { companyId: user.companyId! };
  const runs = await prisma.aiRun.findMany({ where, orderBy: { createdAt: "desc" }, take: 100 });
  const byProvider = Object.entries(runs.reduce<Record<string, number>>((acc, run) => { acc[run.provider] = (acc[run.provider] ?? 0) + 1; return acc; }, {}));
  const byPurpose = Object.entries(runs.reduce<Record<string, number>>((acc, run) => { acc[run.purpose] = (acc[run.purpose] ?? 0) + 1; return acc; }, {}));
  const fallbacks = runs.filter((run) => run.usedFallback).length;
  return <main className="mx-auto max-w-7xl px-6 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-zinc-500">Processing history</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Execution history</h1><p className="mt-2 max-w-3xl text-sm text-zinc-600">DrishtiRecruit keeps hashes and operational metadata for automated and heuristic processing, not copies of candidate or job text. Hiring state, scoring arithmetic, and final decisions remain human-controlled.</p></div><Link className="rounded-xl border border-zinc-300 px-4 py-2 text-sm font-medium" href="/recruiter/dashboard">Dashboard</Link></div>
    <div className="mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wide text-zinc-400">Recent runs</p><p className="mt-2 text-3xl font-semibold">{runs.length}</p></div><div className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wide text-zinc-400">Fallbacks</p><p className="mt-2 text-3xl font-semibold">{fallbacks}</p></div><div className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wide text-zinc-400">Providers</p><p className="mt-2 text-sm font-medium">{byProvider.length ? byProvider.map(([name,count]) => `${name} ${count}`).join(" · ") : "No runs yet"}</p></div></div>
    <section className="mt-8 rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="text-lg font-semibold">Purpose mix</h2><p className="mt-2 text-sm text-zinc-500">{byPurpose.length ? byPurpose.map(([name,count]) => `${humanizeEnum(name)} ${count}`).join(" · ") : "No processing activity has been recorded yet."}</p></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-zinc-200 bg-white"><div className="border-b border-zinc-200 p-5"><h2 className="font-semibold">Recent execution details</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="px-4 py-3">Time</th><th className="px-4 py-3">Purpose</th><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Duration</th><th className="px-4 py-3">Input hash</th><th className="px-4 py-3">Output hash</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-t border-zinc-100"><td className="whitespace-nowrap px-4 py-3 text-xs text-zinc-500">{run.createdAt.toLocaleString()}</td><td className="px-4 py-3">{humanizeEnum(run.purpose)}</td><td className="px-4 py-3">{run.provider}{run.model ? ` · ${run.model}` : ""}</td><td className="px-4 py-3">{run.status}{run.usedFallback ? " · fallback" : ""}</td><td className="px-4 py-3">{run.durationMs} ms</td><td className="px-4 py-3 font-mono text-xs">{run.inputSha256.slice(0, 12)}…</td><td className="px-4 py-3 font-mono text-xs">{run.outputSha256 ? `${run.outputSha256.slice(0, 12)}…` : "—"}</td></tr>)}</tbody></table></div>{!runs.length && <p className="p-6 text-sm text-zinc-500">Run criterion extraction, resume analysis, or interview-question drafting to populate this history.</p>}</section>
  </main>;
}
