export enum UserRole { CANDIDATE="CANDIDATE", RECRUITER="RECRUITER", HIRING_MANAGER="HIRING_MANAGER", INTERVIEWER="INTERVIEWER", ADMIN="ADMIN" }
export enum RequirementPriority { MUST_HAVE="MUST_HAVE", IMPORTANT="IMPORTANT", PREFERRED="PREFERRED" }
export enum RequirementCategory { TECHNICAL_SKILL="TECHNICAL_SKILL", EXPERIENCE="EXPERIENCE", EDUCATION="EDUCATION", COMPETENCY="COMPETENCY", COMMUNICATION="COMMUNICATION", LEADERSHIP="LEADERSHIP", OTHER="OTHER" }
export enum EvidenceSourceType { RESUME="RESUME", PORTFOLIO="PORTFOLIO", ASSESSMENT="ASSESSMENT", INTERVIEW="INTERVIEW", RECRUITER="RECRUITER", CANDIDATE="CANDIDATE" }
export enum EvidenceStrength { WEAK="WEAK", MEDIUM="MEDIUM", STRONG="STRONG" }
export enum CriterionStatus { VERIFIED="VERIFIED", PARTIAL="PARTIAL", WEAK="WEAK", MISSING="MISSING", CONFLICTING="CONFLICTING", OPTIONAL="OPTIONAL" }
export enum VerificationMethod { MCQ="MCQ", CODING="CODING", SQL="SQL", DEBUGGING="DEBUGGING", PRACTICAL="PRACTICAL", INTERVIEW="INTERVIEW", HUMAN_REVIEW="HUMAN_REVIEW", DOCUMENT_CHECK="DOCUMENT_CHECK" }
export enum DecisionReadiness { READY="READY", REVIEW_REQUIRED="REVIEW_REQUIRED", NOT_READY="NOT_READY" }
export enum ApplicationStage { APPLIED="APPLIED", RESUME_SCREENING="RESUME_SCREENING", SHORTLISTED="SHORTLISTED", ASSESSMENT="ASSESSMENT", TECHNICAL_INTERVIEW="TECHNICAL_INTERVIEW", HR_INTERVIEW="HR_INTERVIEW", OFFER="OFFER", HIRED="HIRED", REJECTED="REJECTED" }
export enum OfferStatus { DRAFT="DRAFT", SENT="SENT", ACCEPTED="ACCEPTED", REJECTED="REJECTED", WITHDRAWN="WITHDRAWN" }
