import Link from "next/link";
import { requirePageUser } from "@/lib/auth/page";
import { MetricCard } from "@/components/MetricCard";
import { getAssessmentAnalytics } from "@/services/assessment/assessmentAnalytics";

export default async function AssessmentAnalyticsPage() {
  const user = await requirePageUser(["RECRUITER", "HIRING_MANAGER", "ADMIN"]);
  const analytics = await getAssessmentAnalytics(user.role === "ADMIN" ? null : user.companyId);
  return <main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-zinc-500">Assessment intelligence</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Assessment analytics</h1><p className="mt-2 text-sm text-zinc-500">Completion, score and monitoring signals for standardized verification attempts.</p></div><Link href="/recruiter/analytics" className="rounded-xl border border-zinc-300 px-4 py-2 text-sm font-medium">Hiring analytics</Link></div>
    <div className="mt-8 grid gap-4 md:grid-cols-4"><MetricCard label="Assigned" value={String(analytics.totals.assigned)} detail={`${analytics.totals.started} started`}/><MetricCard label="Completion" value={`${Math.round(analytics.totals.completionRate)}%`} detail={`${analytics.totals.submitted} submitted`}/><MetricCard label="Average score" value={analytics.totals.submitted ? `${Math.round(analytics.totals.averageScore)}%` : "—"} detail="Submitted attempts only"/><MetricCard label="Avg tab switches" value={analytics.totals.started ? analytics.totals.averageTabSwitches.toFixed(1) : "—"} detail="Monitoring signal, not automatic misconduct"/></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="text-lg font-semibold">By verification method</h2><div className="mt-4 space-y-3">{analytics.byMethod.length === 0 ? <p className="text-sm text-zinc-500">No assessment data yet.</p> : analytics.byMethod.map((row) => <div key={row.method} className="rounded-xl bg-zinc-50 p-4"><div className="flex justify-between text-sm"><span className="font-medium">{row.method}</span><span>{row.attempts} question exposure{row.attempts===1?"":"s"}</span></div><p className="mt-1 text-xs text-zinc-500">{row.submitted} submitted · average {row.scoreCount ? `${Math.round(row.averageScore)}%` : "—"}</p></div>)}</div></section><section className="rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="text-lg font-semibold">By requirement</h2><div className="mt-4 space-y-3">{analytics.byRequirement.map((row) => <div key={row.name} className="flex items-center justify-between rounded-xl bg-zinc-50 p-4 text-sm"><div><p className="font-medium">{row.name}</p><p className="text-xs text-zinc-500">{row.attempts} linked question exposure{row.attempts===1?"":"s"}</p></div><span className="font-semibold">{row.scoreCount ? `${Math.round(row.averageScore)}%` : "—"}</span></div>)}</div></section></div>
    <section className="mt-6 rounded-2xl border border-zinc-200 bg-white p-6"><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-400">Review signal</p><h2 className="mt-1 text-lg font-semibold">High answer similarity</h2><p className="mt-1 text-sm text-zinc-500">Long free-text/code answers to the same question with unusually high token-shingle overlap. This is a manual review signal, not a plagiarism or misconduct finding.</p></div><div className="mt-4 space-y-3">{analytics.similaritySignals.length === 0 ? <p className="text-sm text-zinc-500">No high-similarity answer pairs detected in the current tenant data.</p> : analytics.similaritySignals.map((row, index) => <div key={`${row.candidateA}-${row.candidateB}-${index}`} className="rounded-xl border border-zinc-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{row.candidateA} ↔ {row.candidateB}</p><p className="mt-1 text-xs text-zinc-500">{row.assessment} · {row.question.slice(0, 100)}{row.question.length > 100 ? "…" : ""}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-800">{Math.round(row.similarity)}% overlap</span></div><p className="mt-2 text-xs text-zinc-400">{row.shared} shared normalized 5-token shingles · review context before drawing any conclusion</p></div>)}</div></section>
    <section className="mt-6 rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="text-lg font-semibold">Recent attempts</h2><div className="mt-4 divide-y divide-zinc-100">{analytics.recent.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><div><p className="font-medium">{row.assessment}</p><p className="text-xs text-zinc-500">{row.job} · {row.status} · {row.createdAt.toLocaleString()}</p></div><div className="text-right text-xs text-zinc-500"><p>{row.score == null ? "Not scored" : `Score ${Math.round(row.score)}%`}</p><p>{row.tabSwitches} tab switch{row.tabSwitches===1?"":"es"}</p></div></div>)}</div></section>
  </main>;
}
