import { requirePageUser } from "@/lib/auth/page";
import { prisma } from "@/lib/prisma";
import { PrivacyActions } from "@/components/PrivacyActions";

export default async function CandidatePrivacyPage() {
  const user = await requirePageUser(["CANDIDATE"]);
  const record = await prisma.user.findUnique({ where: { id: user.id }, select: { deletionRequestedAt: true, candidate: { select: { _count: { select: { applications: true, resumes: true } } } } } });
  return <main className="mx-auto max-w-3xl px-6 py-10"><p className="text-sm text-zinc-500">Candidate portal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Privacy & data</h1><p className="mt-3 text-sm leading-6 text-zinc-600">Review the data DrishtiRecruit holds for your candidate account. Exports contain your own account, application and hiring-process records plus processing metadata connected to your applications. They do not expose other candidates or private interviewer accounts, and this history does not duplicate raw resume text.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wide text-zinc-400">Applications</p><p className="mt-2 text-2xl font-semibold">{record?.candidate?._count.applications ?? 0}</p></div><div className="rounded-2xl border border-zinc-200 bg-white p-5"><p className="text-xs uppercase tracking-wide text-zinc-400">Resume versions</p><p className="mt-2 text-2xl font-semibold">{record?.candidate?._count.resumes ?? 0}</p></div></div><div className="mt-6"><PrivacyActions requestedAt={record?.deletionRequestedAt?.toISOString() ?? null}/></div><div className="mt-6 rounded-2xl bg-zinc-50 p-5 text-xs leading-6 text-zinc-500">This hackathon build provides export and deletion-request workflows, but does not claim compliance with any specific privacy law. Real deployment requires organization-specific retention rules, legal review and verified deletion procedures.</div></main>;
}
