import Link from "next/link";

const faq = [
  ["Does DrishtiRecruit make the final hiring decision?", "No. DrishtiRecruit organizes evidence, measures coverage, and surfaces unresolved criteria. Authorized people own the final decision."],
  ["Is missing resume evidence treated as poor ability?", "No. Missing evidence is represented as unverified or insufficient evidence, not as proof that a candidate lacks a skill."],
  ["Why separate Fit from Evidence Coverage?", "A candidate can appear strongly aligned while the available proof is incomplete. Keeping the measures separate makes that uncertainty visible."],
  ["How are candidates compared consistently?", "Controlled verification uses approved, criterion-linked assessments and interview workflows rather than arbitrary candidate-specific scoring."],
];

export default function Home() {
  return <main>
    <section className="mx-auto grid min-h-[72vh] max-w-7xl items-center gap-12 px-5 py-16 sm:px-6 lg:grid-cols-[1.02fr_.98fr] lg:py-24">
      <div><div className="mb-5 inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-[11px] font-bold text-indigo-700">Evidence-backed applicant tracking</div><h1 className="max-w-4xl text-5xl font-bold tracking-[-.05em] text-zinc-950 md:text-7xl">Know what is proven. Know what still needs verification.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-600">DrishtiRecruit separates apparent job fit from supporting evidence and decision readiness, then guides teams toward the exact gaps that still matter.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="btn-primary px-5 py-3">Create workspace</Link><Link href="/jobs" className="btn-secondary px-5 py-3">Browse open roles</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs text-zinc-500"><span>Recruiter-approved criteria</span><span>Evidence provenance</span><span>Human-owned decisions</span></div></div>
      <ProductPreview/>
    </section>

    <section className="border-y border-zinc-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="page-eyebrow">A different decision layer</p><h2 className="mt-2 text-3xl font-bold tracking-tight">One hiring process, one evidence model.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-zinc-600">Resume evidence, standardized assessment results, and structured interview notes all map back to the same recruiter-approved criteria.</p></div><div className="grid gap-3 sm:grid-cols-2"><Feature title="Role criteria" text="Turn the role into explicit criteria that recruiters review before they affect evaluation."/><Feature title="Evidence record" text="Keep every important conclusion traceable to resume, assessment, interview, portfolio, or human evidence."/><Feature title="Decision coverage" text="See which required criteria are sufficiently evaluated and which remain open."/><Feature title="Verification plan" text="Choose standardized verification for unresolved criteria without handing the final decision to automation."/></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><p className="page-eyebrow">From application to decision</p><h2 className="mt-2 text-3xl font-bold tracking-tight">The workflow gets more certain as evidence accumulates.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-zinc-600">DrishtiRecruit does not treat resume ranking as the finish line. It keeps the evidence state visible throughout assessments and interviews.</p></div><ol className="space-y-3">{["Create and approve role criteria","Map resume evidence to each criterion","Detect missing or conflicting evidence","Verify gaps through structured assessment or interview","Preserve the human decision with its evidence context"].map((item,index)=><li key={item} className="surface-card flex items-center gap-4 p-4"><span className="grid h-8 w-8 flex-none place-items-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{index+1}</span><span className="text-sm font-semibold">{item}</span></li>)}</ol></div></section>

    <section className="mx-auto max-w-5xl px-5 py-16 sm:px-6"><p className="page-eyebrow">FAQ</p><h2 className="mt-2 text-3xl font-bold tracking-tight">How the evidence model works</h2><div className="mt-7 divide-y divide-zinc-200 rounded-2xl border border-zinc-200 bg-white px-6">{faq.map(([question,answer])=><details key={question} className="py-5"><summary className="cursor-pointer font-semibold">{question}</summary><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-600">{answer}</p></details>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-6"><div className="rounded-3xl bg-gradient-to-br from-indigo-700 to-violet-700 p-8 text-white shadow-xl md:p-12"><p className="text-sm opacity-70">DrishtiRecruit</p><h2 className="mt-2 max-w-2xl text-3xl font-bold tracking-tight">Move from resume matching to evidence-backed hiring.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100">Make the difference between apparent fit and verified decision evidence visible to every hiring team.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/register" className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-indigo-800">Create workspace</Link><Link href="/login" className="rounded-xl border border-white/30 px-5 py-3 text-sm font-semibold">Sign in</Link></div></div></section>
    <footer className="border-t border-zinc-200"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-8 text-sm text-zinc-500 sm:px-6"><span>DrishtiRecruit · Evidence-backed ATS</span><div className="flex gap-4"><Link href="/jobs">Open roles</Link><Link href="/docs">Documentation</Link><Link href="/login">Sign in</Link></div></div></footer>
  </main>;
}

function Feature({ title, text }: { title: string; text: string }) { return <div className="surface-card p-5"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-600">{text}</p></div>; }
function ProductPreview() { const rows = [["Node.js","strong","strong","medium","Verified"],["PostgreSQL","strong","medium","strong","Verified"],["Docker","weak","strong","none","Partial"],["Security design","none","none","none","Missing"]]; return <div className="surface-card overflow-hidden rounded-[26px] p-5 shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-zinc-500">Backend Engineer</p><h2 className="mt-1 text-lg font-bold">Priya Sharma</h2></div><span className="status-pill status-warning">Not ready</span></div><div className="mt-5 grid grid-cols-3 gap-2"><PreviewScore label="Fit" value="89%" tone="fit"/><PreviewScore label="Evidence" value="68%" tone="evidence"/><PreviewScore label="Decision" value="41%" tone="decision"/></div><div className="mt-5 overflow-hidden rounded-xl border border-zinc-200"><div className="grid grid-cols-[1.3fr_repeat(3,.6fr)_1fr] bg-zinc-50 px-3 py-2 text-[8px] font-bold uppercase tracking-wide text-zinc-400"><span>Criterion</span><span>Resume</span><span>Test</span><span>Interview</span><span>Status</span></div>{rows.map(([name,a,b,c,status])=><div key={name} className="grid grid-cols-[1.3fr_repeat(3,.6fr)_1fr] items-center border-t border-zinc-100 px-3 py-3 text-[10px]"><strong>{name}</strong><Dot strength={a}/><Dot strength={b}/><Dot strength={c}/><span className={status==="Verified"?"text-emerald-700":status==="Missing"?"text-red-600":"text-amber-700"}>{status}</span></div>)}</div><div className="mt-4 rounded-xl bg-indigo-50 p-4"><p className="text-[9px] font-bold uppercase tracking-wide text-indigo-500">Next best action</p><p className="mt-1 text-sm font-bold text-indigo-950">Verify Security Design</p><p className="mt-1 text-[11px] leading-5 text-indigo-700">A must-have criterion has no supporting evidence yet.</p></div></div>; }
function PreviewScore({label,value,tone}:{label:string;value:string;tone:"fit"|"evidence"|"decision"}) { const cls=tone==="fit"?"bg-[var(--fit-soft)] text-[var(--fit)]":tone==="evidence"?"bg-[var(--evidence-soft)] text-[var(--evidence)]":"bg-[var(--decision-soft)] text-[var(--decision)]"; return <div className={`rounded-xl p-3 ${cls}`}><p className="text-[8px] font-bold uppercase tracking-wide opacity-70">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
function Dot({strength}:{strength:string}) { if(strength==="none") return <span className="text-zinc-300">—</span>; return <span className={`source-dot ${strength}`}/>; }
