"use client";
import { useState } from "react";

type Preview = { policyDays:number; cutoff:string; expiredVerificationTokens:number; expiredPasswordResetTokens:number; expiredSessions:number; oldDeliveredEmails:number; oldReadNotifications:number; pendingDeletionRequests:number };
export function AdminRetentionPanel({ initial }: { initial: Preview }) {
  const [preview, setPreview] = useState(initial); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function refresh() { const r = await fetch("/api/admin/retention", { cache:"no-store" }); const b = await r.json(); if (r.ok) setPreview(b.data ?? b); }
  async function cleanup() { if (!window.confirm("Delete only the expired operational records shown in this preview? Hiring evidence and audit history will be preserved.")) return; setBusy(true); setMessage(""); try { const r=await fetch("/api/admin/retention", { method:"POST" }); const b=await r.json(); if(!r.ok) throw new Error(b?.error??"Cleanup failed"); const d=b.data??b; setMessage(`Deleted ${d.verificationTokensDeleted+d.passwordResetTokensDeleted+d.sessionsDeleted+d.emailMessagesDeleted+d.notificationsDeleted} expired operational records. Hiring evidence was not deleted.`); await refresh(); } catch(e){setMessage(e instanceof Error?e.message:"Cleanup failed");} finally{setBusy(false);} }
  const total=preview.expiredVerificationTokens+preview.expiredPasswordResetTokens+preview.expiredSessions+preview.oldDeliveredEmails+preview.oldReadNotifications;
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-zinc-50 p-4"><p className="text-xs text-zinc-400">Operational records eligible</p><p className="mt-1 text-2xl font-semibold">{total}</p></div><div className="rounded-xl bg-zinc-50 p-4"><p className="text-xs text-zinc-400">Policy window</p><p className="mt-1 text-2xl font-semibold">{preview.policyDays}d</p></div><div className="rounded-xl bg-zinc-50 p-4"><p className="text-xs text-zinc-400">Deletion requests</p><p className="mt-1 text-2xl font-semibold">{preview.pendingDeletionRequests}</p></div></div><div className="text-xs leading-6 text-zinc-500">Cleanup covers expired/used auth tokens, expired/revoked sessions, old delivered/failed email outbox rows and old read notifications. It deliberately does not delete applications, EvidenceLedger entries, DecisionTrace records or audit logs.</div><div className="flex flex-wrap items-center gap-3"><button disabled={busy||total===0} onClick={cleanup} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-40">{busy?"Cleaning…":"Run operational cleanup"}</button><button onClick={refresh} className="rounded-xl border border-zinc-300 px-4 py-2 text-sm">Refresh preview</button>{message&&<span className="text-xs text-zinc-500">{message}</span>}</div></div>;
}
