"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
const list = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
export function CandidateProfileForm({ profile }: { profile: { name: string; phone: string | null; location: string | null; education: unknown; experience: unknown; skills: string[]; certifications: unknown; portfolioUrl: string | null; githubUrl: string | null; linkedinUrl: string | null; coverLetter: string | null } }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const form = new FormData(event.currentTarget); const lines = (name: string) => String(form.get(name) ?? "").split("\n").map((v) => v.trim()).filter(Boolean); const payload = { name: String(form.get("name") ?? ""), phone: String(form.get("phone") ?? ""), location: String(form.get("location") ?? ""), education: lines("education"), experience: lines("experience"), skills: lines("skills"), certifications: lines("certifications"), portfolioUrl: String(form.get("portfolioUrl") ?? ""), githubUrl: String(form.get("githubUrl") ?? ""), linkedinUrl: String(form.get("linkedinUrl") ?? ""), coverLetter: String(form.get("coverLetter") ?? "") }; const response = await fetch("/api/candidate/profile", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) { setMessage(body.error ?? "Update failed"); return; } setMessage("Profile updated."); router.refresh(); }
  return <form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field name="name" label="Name" value={profile.name} required/><Field name="phone" label="Phone" value={profile.phone ?? ""}/><Field name="location" label="Location" value={profile.location ?? ""}/><Field name="portfolioUrl" label="Portfolio" value={profile.portfolioUrl ?? ""}/><Field name="githubUrl" label="GitHub" value={profile.githubUrl ?? ""}/><Field name="linkedinUrl" label="LinkedIn" value={profile.linkedinUrl ?? ""}/><Area name="skills" label="Skills (one per line)" value={profile.skills}/><Area name="education" label="Education (one item per line)" value={list(profile.education)}/><Area name="experience" label="Experience (one item per line)" value={list(profile.experience)}/><Area name="certifications" label="Certifications (one per line)" value={list(profile.certifications)}/><label className="text-sm md:col-span-2"><span className="mb-1 block font-medium">Cover letter / profile note</span><textarea name="coverLetter" rows={5} defaultValue={profile.coverLetter ?? ""} className="w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label><div className="md:col-span-2 flex items-center gap-3"><button className="rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-medium text-white">Save profile</button>{message && <span className="text-sm text-zinc-600">{message}</span>}</div></form>;
}
function Field({ name, label, value, required=false }: { name:string; label:string; value:string; required?:boolean }) { return <label className="text-sm"><span className="mb-1 block font-medium">{label}</span><input name={name} defaultValue={value} required={required} className="w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>; }
function Area({ name, label, value }: { name:string; label:string; value:string[] }) { return <label className="text-sm"><span className="mb-1 block font-medium">{label}</span><textarea name={name} rows={4} defaultValue={value.join("\n")} className="w-full rounded-xl border border-zinc-300 px-3 py-2.5"/></label>; }
