"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function DecisionPanel({ applicationId, readiness, decisionCoverage, unresolved, conflicts }: { applicationId: string; readiness: string; decisionCoverage: number; unresolved: string[]; conflicts: string[] }) {
  const router = useRouter(); const [decision, setDecision] = useState<"HIRE"|"REJECT"|"HOLD">("HOLD"); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const overrideLikely = decision !== "HOLD" && readiness !== "READY";
  async function submit() { setBusy(true); setMessage(""); const response = await fetch(`/api/applications/${applicationId}/decisions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ humanDecision: decision, overrideReason: reason || undefined }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Decision could not be recorded"); return; } setMessage("Human decision recorded with an immutable evidence snapshot."); router.refresh(); }
  return <section className="rounded-2xl border border-zinc-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-400">DecisionTrace</p><h2 className="mt-1 text-lg font-semibold">Human decision</h2></div><span className={`rounded-full px-3 py-1 text-xs ${readiness === "READY" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{readiness} · {Math.round(decisionCoverage)}%</span></div>{(unresolved.length > 0 || conflicts.length > 0) && <div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{unresolved.length > 0 && <p>Unresolved must-haves: {unresolved.join(", ")}</p>}{conflicts.length > 0 && <p>Conflicting must-haves: {conflicts.join(", ")}</p>}</div>}<div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr]"><select value={decision} onChange={(e) => setDecision(e.target.value as typeof decision)} className="rounded-xl border border-zinc-300 bg-white p-3 text-sm"><option value="HOLD">Hold / gather evidence</option><option value="HIRE">Proceed to offer</option><option value="REJECT">Reject</option></select><textarea value={reason} onChange={(e) => setReason(e.target.value)} rows={3} placeholder={overrideLikely ? "Required: explain why you are overriding incomplete decision coverage" : "Decision note (optional)"} className="rounded-xl border border-zinc-300 p-3 text-sm"/></div><button onClick={submit} disabled={busy || (overrideLikely && reason.trim().length < 5)} className="mt-3 rounded-xl bg-zinc-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-40">{busy ? "Recording…" : "Record human decision"}</button>{message && <p className="mt-2 text-sm text-zinc-500">{message}</p>}<p className="mt-3 text-xs leading-5 text-zinc-400">DrishtiRecruit does not make the final hiring decision. This action records the authorized human decision and the evidence state available at that moment.</p></section>;
}
