"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Item = { requirementId: string; name: string; question: string; reason: string };
export function InterviewScorecard({ interviewId, items }: { interviewId: string; items: Item[] }) {
  const router = useRouter(); const [scores, setScores] = useState<Record<string, number>>({}); const [notes, setNotes] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit() { setBusy(true); setMessage(""); const response = await fetch(`/api/interviews/${interviewId}/scorecards`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scores: items.filter((i) => scores[i.requirementId]).map((i) => ({ requirementId: i.requirementId, score: scores[i.requirementId], evidenceNote: notes[i.requirementId] ?? "" })) }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) { setMessage(body.error ?? "Could not submit scorecard"); return; } setMessage(`Submitted. Decision coverage is now ${Math.round(body.data.decisionCoverage)}%.`); router.refresh(); }
  return <div className="space-y-4">{items.map((item) => <section key={item.requirementId} className="rounded-2xl border border-zinc-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-zinc-400">{item.name}</p><p className="mt-2 font-medium leading-7">{item.question}</p></div><span className="h-fit rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{item.reason}</span></div><div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr]"><select value={scores[item.requirementId] ?? ""} onChange={(e) => setScores((current) => ({ ...current, [item.requirementId]: Number(e.target.value) }))} className="rounded-xl border border-zinc-300 bg-white p-3 text-sm"><option value="">Score 1–5</option>{[1,2,3,4,5].map((n) => <option key={n} value={n}>{n}/5</option>)}</select><textarea rows={3} value={notes[item.requirementId] ?? ""} onChange={(e) => setNotes((current) => ({ ...current, [item.requirementId]: e.target.value }))} placeholder="Evidence note: record what the candidate demonstrated, not personality impressions." className="rounded-xl border border-zinc-300 p-3 text-sm"/></div></section>)}<button disabled={busy || !items.some((i) => scores[i.requirementId])} onClick={submit} className="rounded-xl bg-zinc-950 px-5 py-3 text-sm font-medium text-white disabled:opacity-40">{busy ? "Submitting…" : "Submit structured scorecard"}</button>{message && <p className="text-sm text-zinc-500">{message}</p>}</div>;
}
