"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
export function JobCreateForm(){
  const router=useRouter(); const[busy,setBusy]=useState(false); const[error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const salaryMin=String(f.get("salaryMin")??"").trim();const salaryMax=String(f.get("salaryMax")??"").trim();const deadline=String(f.get("deadline")??"").trim();const data={title:String(f.get("title")??""),department:String(f.get("department")??""),location:String(f.get("location")??""),employmentType:String(f.get("employmentType")??""),workMode:String(f.get("workMode")??""),experienceText:String(f.get("experienceText")??""),salaryMin:salaryMin?Number(salaryMin):undefined,salaryMax:salaryMax?Number(salaryMax):undefined,deadline:deadline?new Date(`${deadline}T23:59:59Z`).toISOString():undefined,description:String(f.get("description")??"")};const r=await fetch("/api/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const b=await r.json();setBusy(false);if(!r.ok){setError(b.error??"Could not create job");return;}router.push(`/recruiter/jobs/${b.data.id}/requirements`);router.refresh();}
  return <form onSubmit={submit} className="space-y-5"><Input name="title" label="Job title"/><div className="grid gap-4 md:grid-cols-2"><Input name="department" label="Department" required={false}/><Input name="location" label="Location" required={false}/><Input name="employmentType" label="Employment type" required={false}/><Input name="workMode" label="Work mode" required={false}/><Input name="experienceText" label="Experience required" required={false}/><Input name="deadline" label="Application deadline" type="date" required={false}/><Input name="salaryMin" label="Minimum salary" type="number" required={false}/><Input name="salaryMax" label="Maximum salary" type="number" required={false}/></div><div><label className="mb-1 block text-sm font-medium">Job description</label><textarea name="description" required minLength={40} rows={12} className="w-full rounded-xl border border-zinc-300 bg-white p-3" placeholder="Describe responsibilities, must-have skills and preferred skills…"/></div>{error&&<p className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="rounded-xl bg-zinc-950 px-5 py-3 text-sm font-medium text-white">{busy?"Extracting requirements…":"Create job & extract criteria"}</button></form>;
}
function Input({name,label,required=true,type="text"}:{name:string;label:string;required?:boolean;type?:string}){return <div><label className="mb-1 block text-sm font-medium">{label}</label><input name={name} type={type} required={required} className="w-full rounded-xl border border-zinc-300 bg-white px-3 py-3"/></div>}
