import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth/rbac";
import { buildSimpleTextPdf } from "@/lib/pdf/simplePdf";
import { fail } from "@/lib/http/route";
import { canViewOfferDocument } from "@/services/access/policies";

function salaryText(value: unknown) {
  if (value == null) return "As discussed";
  return `INR ${Number(value).toLocaleString("en-IN")}`;
}

export async function GET(_request: Request, { params }: { params: Promise<{ offerId: string }> }) {
  try {
    const user = await requireUser();
    const { offerId } = await params;
    const offer = await prisma.offerLetter.findUnique({
      where: { id: offerId },
      include: { application: { include: { candidate: { include: { user: true } }, job: { include: { company: true } } } } },
    });
    if (!offer) throw new Response("Offer not found", { status: 404 });
    if (!canViewOfferDocument(user, { candidateUserId: offer.application.candidate.userId, companyId: offer.application.job.companyId })) throw new Response("Forbidden", { status: 403 });
    const benefits = Array.isArray(offer.benefits) ? offer.benefits.map(String) : [];
    const lines = [
      "DRISHTIRECRUIT OFFER LETTER",
      "",
      `Company: ${offer.application.job.company.name}`,
      `Candidate: ${offer.application.candidate.user.name}`,
      `Role: ${offer.roleTitle}`,
      `Location: ${offer.location ?? offer.application.job.location ?? "As discussed"}`,
      `Salary: ${salaryText(offer.salary)}`,
      `Joining date: ${offer.joiningDate ? offer.joiningDate.toISOString().slice(0, 10) : "As discussed"}`,
      "",
      "Benefits:",
      ...(benefits.length ? benefits.map((item) => `- ${item}`) : ["- As per company policy"]),
      "",
      `Offer status: ${offer.status}`,
      "Generated by DrishtiRecruit. Final legal terms remain subject to the employer's approved offer template.",
    ];
    const pdf = buildSimpleTextPdf(lines);
    return new Response(new Uint8Array(pdf), { headers: { "content-type": "application/pdf", "content-disposition": `attachment; filename="drishtirecruit-offer-${offer.id}.pdf"`, "cache-control": "private, no-store" } });
  } catch (error) { return fail(error); }
}
