import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

export default async function CareersPage({ params }: { params: Promise<{ companyId: string }> }) {
  const { companyId } = await params;
  const company = await prisma.company.findUnique({ where: { id: companyId }, include: { jobs: { where: { status: "OPEN", OR: [{ deadline: null }, { deadline: { gte: new Date() } }] }, orderBy: { createdAt: "desc" }, include: { requirements: { where: { recruiterApproved: true } } } } } });
  if (!company) notFound();
  const locations = Array.isArray(company.officeLocations) ? company.officeLocations.filter((item): item is string => typeof item === "string") : [];
  return <main className="mx-auto max-w-6xl px-6 py-14"><section className="rounded-3xl border border-zinc-200 bg-white p-8 md:p-10"><p className="text-sm font-medium text-zinc-500">Careers at</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{company.name}</h1>{company.description && <p className="mt-5 max-w-3xl leading-7 text-zinc-600">{company.description}</p>}<div className="mt-6 flex flex-wrap gap-2 text-xs text-zinc-600">{company.industry && <span className="rounded-full bg-zinc-100 px-3 py-1.5">{company.industry}</span>}{company.size && <span className="rounded-full bg-zinc-100 px-3 py-1.5">{company.size} employees</span>}{locations.map((location) => <span key={location} className="rounded-full bg-zinc-100 px-3 py-1.5">{location}</span>)}</div>{company.website && <a href={company.website} className="mt-6 inline-block text-sm font-medium underline underline-offset-4">Company website</a>}</section>
    <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-zinc-500">Open opportunities</p><h2 className="mt-1 text-2xl font-semibold">Join the team</h2></div><span className="text-sm text-zinc-500">{company.jobs.length} open role{company.jobs.length===1?"":"s"}</span></div><div className="mt-5 grid gap-4">{company.jobs.length === 0 ? <div className="rounded-2xl border border-zinc-200 bg-white p-6 text-sm text-zinc-500">No open roles right now.</div> : company.jobs.map((job) => <article key={job.id} className="rounded-2xl border border-zinc-200 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-zinc-500">{job.department ?? "Role"}</p><h3 className="mt-1 text-xl font-semibold">{job.title}</h3><p className="mt-2 text-sm text-zinc-500">{[job.location, job.workMode, job.employmentType].filter(Boolean).join(" · ")}</p></div><Link href={`/jobs?q=${encodeURIComponent(job.title)}`} className="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-medium text-white">View & apply</Link></div><p className="mt-4 line-clamp-3 text-sm leading-6 text-zinc-600">{job.description}</p><div className="mt-4 flex flex-wrap gap-2">{job.requirements.filter((r)=>r.priority === "MUST_HAVE").slice(0,6).map((r)=><span key={r.id} className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs">{r.name}</span>)}</div></article>)}</div></section>
  </main>;
}
