import { requirePageUser } from "@/lib/auth/page";
import { getRecruitingAnalytics } from "@/services/analytics/analyticsService";
import { MetricCard } from "@/components/MetricCard";
import Link from "next/link";
import { humanizeEnum } from "@/lib/ui/labels";

const ORDER = ["APPLIED","RESUME_SCREENING","SHORTLISTED","ASSESSMENT","TECHNICAL_INTERVIEW","HR_INTERVIEW","OFFER","HIRED","REJECTED"];
const BANDS = ["0-49", "50-69", "70-84", "85-100"] as const;

function CoverageBars({ label, values, total, tone }: { label: string; values: Record<(typeof BANDS)[number], number>; total: number; tone: "fit" | "evidence" | "decision" }) {
  const color = tone === "fit" ? "var(--fit)" : tone === "evidence" ? "var(--evidence)" : "var(--decision)";
  return <div><div className="mb-2 flex items-center justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-[10px] text-zinc-400">{total} analysed</span></div><div className="space-y-2">{BANDS.map((band) => { const count = values[band] ?? 0; const width = total ? (count / total) * 100 : 0; return <div key={band} className="grid grid-cols-[58px_1fr_34px] items-center gap-2 text-xs"><span className="text-zinc-500">{band}</span><div className="h-2 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full" style={{ width: `${width}%`, background: color }}/></div><span className="metric-number text-right font-semibold">{count}</span></div>})}</div></div>;
}

export default async function AnalyticsPage() {
  const user = await requirePageUser(["RECRUITER", "HIRING_MANAGER", "ADMIN"]);
  const analytics = await getRecruitingAnalytics(user.role === "ADMIN" ? null : user.companyId);
  const maxStage = Math.max(1, ...Object.values(analytics.stageCounts));
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="page-header"><div><p className="page-eyebrow">Decision insights</p><h1 className="page-title">Recruiting analytics</h1><p className="page-description">Operational funnel metrics plus the signals that make DrishtiRecruit different: apparent fit, supporting evidence, and decision coverage.</p></div><div className="flex gap-2"><Link href="/recruiter/assessments/analytics" className="btn-secondary">Assessment analytics</Link><a href="/api/reports/recruiting.csv" className="btn-primary">Export CSV</a></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Applications" value={String(analytics.totals.applications)} detail={`${analytics.totals.jobs} recorded jobs`}/><MetricCard label="Hired" value={String(analytics.totals.hired)} detail="Current hired applications"/><MetricCard kind="decision" label="Offer acceptance" value={`${Math.round(analytics.offerAcceptanceRate)}%`} progress={analytics.offerAcceptanceRate} detail="Accepted / answered offers"/><MetricCard label="Avg time to hire" value={analytics.averageTimeToHireDays ? `${analytics.averageTimeToHireDays.toFixed(1)}d` : "—"} detail="Application to hired stage"/></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_1.08fr]"><section className="surface-card p-5"><p className="section-kicker">DrishtiRecruit signal</p><h2 className="section-heading mt-1">Fit vs evidence vs decision coverage</h2><p className="section-description">Each metric has its own visual identity so teams do not confuse apparent alignment with supporting proof or decision readiness.</p><div className="mt-5 space-y-5"><CoverageBars label="Fit score" values={analytics.coverageBands.fit} total={analytics.totals.applications} tone="fit"/><CoverageBars label="Evidence coverage" values={analytics.coverageBands.evidence} total={analytics.totals.applications} tone="evidence"/><CoverageBars label="Decision coverage" values={analytics.coverageBands.decision} total={analytics.totals.applications} tone="decision"/></div></section>
      <section className="surface-card p-5"><p className="section-kicker">Priority review</p><h2 className="section-heading mt-1">High apparent fit, weaker evidence</h2><p className="section-description">This is a verification queue, not a rejection list.</p><div className="mt-4 space-y-2">{analytics.evidenceRiskCandidates.length === 0 ? <p className="text-sm text-zinc-500">No candidates currently meet the review threshold.</p> : analytics.evidenceRiskCandidates.map((row) => <Link key={row.applicationId} href={`/recruiter/applications/${row.applicationId}`} className="block rounded-xl border border-zinc-200 p-3 hover:border-indigo-200 hover:bg-indigo-50/30"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold">{row.candidate}</p><p className="text-[10px] text-zinc-500">{row.job}</p></div><span className="status-pill status-warning">{Math.round(row.gap)}pt gap</span></div><div className="mt-3 grid grid-cols-3 gap-2"><MiniSignal label="Fit" value={row.fitScore} tone="fit"/><MiniSignal label="Evidence" value={row.evidenceCoverage} tone="evidence"/><MiniSignal label="Decision" value={row.decisionCoverage} tone="decision"/></div></Link>)}</div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="surface-card p-5"><h2 className="section-heading">Hiring funnel</h2><div className="mt-5 space-y-3">{ORDER.map((stage) => { const count = analytics.stageCounts[stage] ?? 0; return <div key={stage}><div className="mb-1 flex justify-between text-xs"><span>{humanizeEnum(stage)}</span><span className="metric-number">{count}</span></div><div className="h-2 overflow-hidden rounded bg-zinc-100"><div className="h-full rounded bg-indigo-500" style={{ width: `${(count / maxStage) * 100}%` }}/></div></div>})}</div></section>
      <section className="surface-card p-5"><h2 className="section-heading">Evidence gaps</h2><p className="section-description">Criteria most often left weak, missing, partial, or conflicting.</p><div className="mt-4 space-y-2">{analytics.evidenceGaps.length === 0 ? <p className="text-sm text-zinc-500">No analysed evidence gaps yet.</p> : analytics.evidenceGaps.map((gap) => <div key={gap.name} className="flex items-center justify-between rounded-xl bg-zinc-50 p-3"><div><p className="font-semibold">{gap.name}</p><p className="text-[10px] text-zinc-500">{gap.mustHaveCount} must-have gap{gap.mustHaveCount === 1 ? "" : "s"}</p></div><span className="metric-number text-sm font-bold">{gap.count}</span></div>)}</div></section></div>
    <section className="surface-card mt-5 p-5"><h2 className="section-heading">Evaluation redundancy</h2><p className="section-description">Criteria evidenced through three or more independent source types can be candidates for less repeat questioning when other criteria remain uncovered.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{analytics.evaluationRedundancy.length === 0 ? <p className="text-sm text-zinc-500">No redundancy signal yet.</p> : analytics.evaluationRedundancy.map((item) => <div key={item.name} className="rounded-xl bg-zinc-50 p-4"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-zinc-500">Over-covered in {item.count} application{item.count === 1 ? "" : "s"}</p></div>)}</div></section>
  </main>;
}

function MiniSignal({ label, value, tone }: { label: string; value: number; tone: "fit" | "evidence" | "decision" }) { const cls = tone === "fit" ? "bg-[var(--fit-soft)] text-[var(--fit)]" : tone === "evidence" ? "bg-[var(--evidence-soft)] text-[var(--evidence)]" : "bg-[var(--decision-soft)] text-[var(--decision)]"; return <div className={`rounded-lg p-2 ${cls}`}><p className="text-[9px] font-bold uppercase tracking-wide opacity-70">{label}</p><p className="metric-number mt-0.5 text-sm font-bold">{Math.round(value)}%</p></div>; }
